// GENERATED FILE — DO NOT EDIT BY HAND
// Generated by ml/deployment/step7_export_c_array.py
// Date: 2026-04-13 00:52
// Source: ml/deployment/artifacts/model_float_frozen.tflite
// Model size: 52896 bytes (51.7 KB)
//
// Architecture:
//   ego_dim         = 18   (6 features × 3 stacked frames)
//   peer_feature_dim= 6   per-peer feature count
//   max_peers       = 8   padded peer slots
//   embed_dim       = 32   peer encoder output dim
//   action_dim      = 1   braking signal in [0, 1]
//
// Input tensors (see ObservationBuilder for feature construction):
//   ego      [1][18]   float32
//   peers    [1][8][6] float32
//   peer_mask[1][8]   float32  (1.0=valid, 0.0=padding)
//
// Output tensor:
//   action   [1][1]   float32  braking in [0.0, 1.0]

#pragma once

#include <cstdint>

extern const uint8_t g_model_data[];
extern const uint32_t g_model_data_len;
