"""
Step 7: Export the INT8 TFLite model as a C byte array for inclusion in firmware.

Reads:
  ml/deployment/artifacts/model_int8_dr.tflite   (dynamic-range INT8, validated by step6)
  ml/deployment/artifacts/model_config.json

Writes:
  hardware/src/inference/model_data.h    (C array: g_model_data + g_model_data_len)
  hardware/src/inference/model_data.cc   (definition)

Note: step6 selected model_int8_dr.tflite (dynamic-range) over model_int8.tflite (PTQ)
because the PTQ model exceeded the max_ae threshold. Both use float32 I/O on ESP32.

Run from repo root:
  python -m ml.deployment.step7_export_c_array
"""
import argparse
import json
import os
from datetime import datetime


DEFAULT_TFLITE  = "ml/deployment/artifacts/model_int8_dr.tflite"
DEFAULT_CONFIG  = "ml/deployment/artifacts/model_config.json"
DEFAULT_QPARAMS = ""  # DR model has float32 I/O — no quant params needed
DEFAULT_OUT_DIR = "hardware/src/inference"


def tflite_to_c_array(tflite_path: str, config_path: str,
                       qparams_path: str, out_dir: str) -> None:
    with open(tflite_path, "rb") as f:
        model_bytes = f.read()

    with open(config_path) as f:
        cfg = json.load(f)

    qparams = {}
    if os.path.exists(qparams_path):
        with open(qparams_path) as f:
            qparams = json.load(f)

    size_bytes = len(model_bytes)
    size_kb    = size_bytes / 1024

    # Format as C hex array
    hex_rows = []
    for i in range(0, size_bytes, 12):
        chunk = model_bytes[i:i+12]
        hex_rows.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    hex_body = "\n".join(hex_rows)

    os.makedirs(out_dir, exist_ok=True)

    # ------------------------------------------------------------------ #
    # model_data.h                                                         #
    # ------------------------------------------------------------------ #
    input_io_note = ""
    if qparams:
        lines = []
        for inp in qparams.get("inputs", []):
            lines.append(
                f"//   {inp['name']:30s}  scale={inp['scale']:.8f}  "
                f"zero_point={inp['zero_point']}"
            )
        for out in qparams.get("outputs", []):
            lines.append(
                f"//   {out['name']:30s}  scale={out['scale']:.8f}  "
                f"zero_point={out['zero_point']}"
            )
        input_io_note = "\n// Quantization parameters (INT8 I/O):\n" + "\n".join(lines) + "\n"

    header = f"""// GENERATED FILE — DO NOT EDIT BY HAND
// Generated by ml/deployment/step7_export_c_array.py
// Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}
// Source: {tflite_path}
// Model size: {size_bytes} bytes ({size_kb:.1f} KB)
//
// Architecture:
//   ego_dim         = {cfg['ego_dim']}   (6 features × 3 stacked frames)
//   peer_feature_dim= {cfg['peer_feature_dim']}   per-peer feature count
//   max_peers       = {cfg['max_peers']}   padded peer slots
//   embed_dim       = {cfg['embed_dim']}   peer encoder output dim
//   action_dim      = {cfg['action_dim']}   braking signal in [0, 1]
//
// Input tensors (see ObservationBuilder for feature construction):
//   ego      [1][{cfg['ego_dim']}]   float32
//   peers    [1][{cfg['max_peers']}][{cfg['peer_feature_dim']}] float32
//   peer_mask[1][{cfg['max_peers']}]   float32  (1.0=valid, 0.0=padding)
//
// Output tensor:
//   action   [1][{cfg['action_dim']}]   float32  braking in [0.0, 1.0]
{input_io_note}
#pragma once

#include <cstdint>

extern const uint8_t g_model_data[];
extern const uint32_t g_model_data_len;
"""

    source = f"""// GENERATED FILE — DO NOT EDIT BY HAND
// See model_data.h for documentation.

#include "model_data.h"

alignas(8) const uint8_t g_model_data[] = {{
{hex_body}
}};

const uint32_t g_model_data_len = {size_bytes}u;
"""

    header_path = os.path.join(out_dir, "model_data.h")
    source_path = os.path.join(out_dir, "model_data.cc")

    with open(header_path, "w") as f:
        f.write(header)
    with open(source_path, "w") as f:
        f.write(source)

    print(f"C array written:")
    print(f"  {header_path}")
    print(f"  {source_path}")
    print(f"  Model size: {size_bytes} bytes ({size_kb:.1f} KB)")
    print(f"  Flash usage: ~{size_kb:.0f} KB  (ESP32 has 4096 KB flash)")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tflite",   default=DEFAULT_TFLITE)
    parser.add_argument("--config",   default=DEFAULT_CONFIG)
    parser.add_argument("--qparams",  default=DEFAULT_QPARAMS)
    parser.add_argument("--out_dir",  default=DEFAULT_OUT_DIR)
    args = parser.parse_args()
    tflite_to_c_array(args.tflite, args.config, args.qparams, args.out_dir)


if __name__ == "__main__":
    main()
